export const myProjects = [
    {
      projectTitle: "sales management system",
      description:"A robust sales management system built with Laravel and AJAX, featuring tools for efficient sales tracking and management.",
      category: ["laravel", "ajax"],
      imgPath: "./images/sales management.png",
      githubLink:"https://github.com/WaelHamwi/Sales-Management-System",
      iconGithub:"icon-github",
      demo:"https://drive.google.com/file/d/1nOejjYnO80VHT_sKy1qpp0Y4u4S8iO97/view?usp=drive_link",
      item: "a",
    },
    {
      projectTitle: "E-commerce",
      description:"An e-commerce platform developed using Laravel and React, designed for seamless online shopping experiences.",
      category: ["laravel", "react"],
      imgPath: "./images/E-commerce.png",
      iconGithub:"icon-github",
      githubLink:"https://github.com/WaelHamwi/E-commerce-laravel_react",
      demo:"https://drive.google.com/file/d/1ZHdWT4mchLcz_dxCQNb3a7g5KdEhlOd4/view?usp=drive_link",
      item: "b",
    },
    {
      projectTitle: "Wordpress automation",
      description:"Automated WordPress solution with FormCraft integration for streamlined corporate account opening processes.",
      category: ["wordpress", "formCraft"],
      imgPath: "./images/merak.png",
      iconLink:"https://merak.capital/corporate-account-opening-agreement/",
      linkClass:"icon-link",
      demo:"https://drive.google.com/file/d/1G38wkwa2oFq9h93JryE2j5aQ48CFGDiR/view?usp=drive_link",
      item: "c",
    },
    {
      projectTitle: "Wordpress customized theme",
      description:"A customized WordPress theme built with Elementor for enhanced website design and functionality.",
      category: ["wordpress", "elementor"],
      imgPath: "./images/EMERALD.png",
      iconLink:"http://emeraldtech-uae.com/",
      linkClass:"icon-link",
      item: "e",
    },
    {
      projectTitle: "Wordpess Portfolio",
      description:"A personal portfolio website created with WordPress, Phlox, and Elementor showcasing various projects.",
      category: ["wordpress", "phlox", "elementor"],
      imgPath: "./images/wordpressPortfolio.jpg",
      iconGithub:"icon-github",
      githubLink:"https://github.com/WaelHamwi/Portfolio/tree/master",
      item: "f",
    },
    {
      projectTitle: "AI App",
      description:"An AI-powered application developed with Flask for COVID-19 detection and data analysis.",
      category: ["flusk", "ai"],
      imgPath: "./images/Covid-19 App.png",
      iconGithub:"icon-github",
      githubLink:"https://github.com/WaelHamwi/AI-App/tree/master",
      demo:"https://drive.google.com/file/d/1ptjlCNlWtZokim0l48FvAE1Tb8a3LwqJ/view?usp=drive_link",
      item: "g",
    },
    {
      projectTitle: "Web Engineering",
      description: 'Navigation and presentation diagram for National Geographic website.',
      category: ["webEngineer"],
      imgPath: "./images/Navigation.jpg",
      iconGithub:"icon-github",
      githubLink:"https://github.com/WaelHamwi/web-engineering/tree/master",
      item: "h",
    },
    {
      projectTitle: "Data Mining",
      description:"A project implementing data mining techniques and the MVC pattern for efficient data analysis and retrieval.",
      category: ["dataMining"],
      imgPath: "./images/wde.png",
      iconGithub:"icon-github",
      githubLink:"https://github.com/WaelHamwi/Data-Mining-and-MVC-pattern",
      item: "i",
    },
    {
      projectTitle: "Turtle Game",
      description:"A JavaScript-based game featuring a turtle character, showcasing interactive gameplay and programming skills.",
      category: ["JavaScript"],
      imgPath: "./images/turtle.webp",
      iconGithub:"icon-github",
      githubLink:"https://github.com/WaelHamwi/Turtle-game/tree/master",
      item: "i",
    },
  ];