import {
  faBootstrap,
  faGithub,
  faLaravel,
  faPython,
  faReact,
  faWebflow,
  faWordpress,
  faCss3Alt,
} from "@fortawesome/free-brands-svg-icons";

import {
  faProjectDiagram,
  faPuzzlePiece,
  faRobot,
  faRocket,
  faUserShield,
  faSpinner,
  faCoffee,
  faServer,
  faCode,
  faFolderOpen,
  faTerminal,
  faDatabase,
} from "@fortawesome/free-solid-svg-icons";
import { faPhp } from "@fortawesome/free-brands-svg-icons";

export const skills = [
  {
    name: "Filament",
    imgSrc: "./images/filament.jfif",
    icon: faFilament,
    info: "Filament is a robust admin panel for Laravel applications that helps streamline backend development, offering a clean interface and powerful features.",
  },
  {
    name: "Laravel",
    imgSrc: "./images/Laravel-Logo.png",
    icon: faLaravel,
    info: "I mastered Laravel by utilizing its elegant syntax and powerful tools, like Eloquent ORM and Blade templating. This framework transformed my approach to web application development, allowing me to create robust and scalable solutions with ease.",
  },
  {
    name: "PHP",
    imgSrc: "./images/php.png",
    icon: faPhp,
    info: "PHP was my starting point to master Laravel and other programming languages. Its versatility and extensive libraries have allowed me to build dynamic, feature-rich websites and applications that meet diverse client needs.",
  },
  {
    name: "Ajax",
    imgSrc: "./images/ajax.png",
    icon: faSpinner,
    info: "My experience with Ajax has revolutionized the way I develop web applications. By enabling asynchronous data updates, Ajax has allowed me to create fast, responsive, and interactive user experiences that keep users engaged and satisfied.",
  },
  {
    name: "React",
    imgSrc: "./images/react.png",
    icon: faReact,
    info: "After learning Ajax, I wanted more robust solutions, leading me to React. React's reusable components and efficient state management have been key to developing sophisticated, scalable web applications.",
  },
  {
    name: "WordPress",
    imgSrc: "./images/wordpress.png",
    icon: faWordpress,
    info: "WordPress has helped me automate tasks by integrating with DocuSign and Zapier using plugins like Elementor and FormCraft. Its user-friendly interface and extensive plugin ecosystem have enabled me to build and manage a variety of websites effortlessly.",
  },
  {
    name: "jQuery",
    imgSrc: "./images/jquery.png",
    icon: faCoffee,
    info: "Mastering JavaScript led me to jQuery, which drastically simplified code writing and enabled animations. Its concise syntax and powerful features enhanced interactivity in my web projects, making it my longest journey with a framework.",
  },
  {
    name: "Bootstrap",
    imgSrc: "./images/bootstrap.svg",
    icon: faBootstrap,
    info: "Bootstrap revolutionized my front-end development journey with its responsive grid system and pre-designed components, enabling rapid development of mobile-first websites. While I learned Bootstrap, I prefer writing native CSS and Sass to customize my website's format to suit specific needs.",
  },
  {
    name: "Web Engineering",
    imgSrc: "./images/webEngineer.png",
    icon: faWebflow,
    info: "My expertise in web engineering encompasses a comprehensive understanding of both front-end and back-end development. This holistic approach has enabled me to build well-architected and maintainable web solutions, addressing both aesthetic and functional requirements.",
  },
  {
    name: "Git",
    imgSrc: "./images/git.png",
    icon: faGithub,
    info: "Git has been an essential tool in my version control workflow. Mastering Git has allowed me to collaborate seamlessly with other developers, manage code changes efficiently, and maintain a robust history of my projects.",
  },
  {
    name: "Python",
    imgSrc: "./images/python.webp",
    icon: faPython,
    info: "Python was indispensable for my master's project, where I built neural networks and the website. Its versatility facilitated various projects, from web development to data analysis, thanks to its readability and rich libraries, making it my preferred language for efficient problem-solving.",
  },
  {
    name: "Deep Learning",
    imgSrc: "./images/Ai.png",
    icon: faRobot,
    info: "From university to my master's program, I swiftly grasped deep learning concepts. Leveraging frameworks like TensorFlow and Keras, I developed advanced models, including convolutional neural networks (CNN), for data analysis and intelligent predictions.",
  },
  {
    name: "TensorFlow & Keras",
    imgSrc: "./images/tensor.png",
    icon: faRocket,
    info: "TensorFlow opened the door to machine learning and deep learning, and learning Keras, its API, significantly facilitated my work. These tools empowered me to build, train, and deploy neural networks, solving complex problems and contributing to innovative projects.",
  },
  {
    name: "Data Structures",
    imgSrc: "./images/dataStructure.jpg",
    icon: faProjectDiagram,
    info: "Mastering data structures was pivotal after a long journey through university and my master's program. When I built my first website, I finally mastered this approach.",
  },
  {
    name: "Security Awareness",
    imgSrc: "./images/secure.webp",
    icon: faUserShield,
    info: "Security awareness has been crucial in my development process. In a situation where my client was attacked by a hacker, I effectively dealt with the issue due to my understanding of the WordPress folder structure, ensuring the security of the website and protecting user data.",
  },
  {
    name: "Problem Solving",
    imgSrc: "./images/problemSolving.png",
    icon: faPuzzlePiece,
    info: "Problem-solving is at the heart of what I do as a developer. Whether it's debugging code, optimizing performance, or creating innovative solutions, my ability to think critically and tackle challenges head-on has been essential to my success.",
  },
  {
    name: "Expert Server Maintenance Specialist",
    imgSrc: "./images/server.jpg",
    icon: faServer,
    info: "Specializing in maintaining and optimizing server infrastructure for smooth operations and high performance. Expertise includes diagnosing and resolving issues, proactive measures for reliability and security, troubleshooting, capacity planning, performance tuning, and security best practices.",
  },
  {
    name: "Sass",
    imgSrc: "./images/SASS.png",
    icon: faCss3Alt,
    info: "Sass has enhanced my CSS styling capabilities by allowing me to use variables, nested rules, and mixins, making my stylesheets more maintainable and efficient.",
  },
  {
    name: "TypeScript",
    imgSrc: "./images/typescript.png",
    icon: faCode,
    info: "TypeScript has provided me with a robust type system for JavaScript, improving my development experience with better tooling, type checking, and clearer code.",
  },
  {
    name: "Next.js",
    imgSrc: "./images/next-js.svg",
    icon: faFolderOpen,
    info: "Next.js has enabled me to build server-rendered React applications with ease, offering features like static site generation and server-side rendering for optimal performance and SEO.",
  },
  {
    name: "Tailwind CSS",
    imgSrc: "./images/tailwind-css.svg",
    icon: faCss3Alt,
    info: "Tailwind CSS has transformed my approach to styling by providing a utility-first framework that allows for rapid and flexible design without leaving my HTML.",
  },
  {
    name: "Express.js",
    imgSrc: "./images/express.svg",
    icon: faServer,
    info: "Express.js has simplified the development of server-side applications with its minimal and flexible approach, allowing me to build RESTful APIs and web applications efficiently.",
  },
  {
    name: "Node.js",
    imgSrc: "./images/nodejs.png",
    icon: faTerminal,
    info: "Node.js has enabled me to run JavaScript on the server side, allowing for the development of scalable network applications and server-side logic with a unified JavaScript codebase.",
  },
  {
    name: "MongoDB",
    imgSrc: "./images/mongodb.svg",
    icon: faDatabase,
    info: "MongoDB's NoSQL database has been a powerful tool for managing and querying large datasets, providing flexibility with JSON-like documents and easy scalability.",
  },
  {
    name: "Redux",
    imgSrc: "./images/redux-logo.svg",
    icon: faCode,
    info: "Redux has provided a predictable state container for JavaScript apps, allowing me to manage and centralize application state efficiently, particularly in complex React applications.",
  },
  {
    name: "Convex",
    imgSrc: "./images/convex.png",
    icon: faServer,
    info: "Convex simplifies serverless application development with a focus on minimal configuration and real-time updates. It integrates seamlessly with frontend frameworks, streamlining the development process.",
  },
  {
    name: "Alpine.js",
    imgSrc: "./images/alpine.svg",
    icon: faServer,
    info: "Convex simplifies serverless application development with a focus on minimal configuration and real-time updates. It integrates seamlessly with frontend frameworks, streamlining the development process.",
  },
];
